### ISSUE TITLE
Késik a hang

### ISSUE THREAD

**Issue by adrianmihalko** [a-sync/mediaklikk-downloader#3]
Szia,

A letöltött [adásban](https://mediaklikk.hu/video/en-vagyok-itt-2020-01-09-i-adas/) késik a hang, mi lehet a probléma?

**Comment by a-sync** [comment]
Szia, 
más adásoknál nem tapasztalsz hasonlót?  
Esetleg korrumpálódhatott a letöltésed, próbáld meg újra.
Más letöltővel is érdemes megpróbálni, pl. youtube-dl

**Comment by adrianmihalko** [comment]
Köszi, kimondottan csak ezzel az adással próbáltam. Még egyszer megpróbáltam letölteni, de ugyan így hibás volt. Köszi a tippet a youtube-dl-ért.
