### ISSUE TITLE
Nem működik

### ISSUE THREAD

**Issue by kanehu** [a-sync/mediaklikk-downloader#9]
Nekem nem működik itt: https://mediaklikk.hu/video/2021/11/29/isztambuli-menyasszony-3-evad-64-resz

**Comment by a-sync** [comment]
A hiba nálad van :)  
![image](https://user-images.githubusercontent.com/14183614/144342513-c84dfd31-3773-4d9b-bbe7-d6790fc14952.png)
  
Próbáld meg a yt-dlp -vel. 
![image](https://user-images.githubusercontent.com/14183614/144342721-458b396d-1ce6-4ec0-9ac5-47fceff09ce7.png)
